katana_450_6m90a:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointTrajectoryController
    publish_rate: 50 
  
  # Position Controllers ---------------------------------------
  katana_arm_m1_controller:
    type: effort_controllers/JointTrajectoryController
    joint: katana_motor1_pan_joint
    pid: {p: 10.0, i: 4.0, d: 3.0, i_clamp: 0.0}

  katana_arm_m2_controller:
    type: effort_controllers/JointTrajectoryController
    joint: katana_motor2_pan_joint
    pid: {p: 7.0, i: 3.0, d:  2.0, i_clamp: 0.0}

  katana_arm_m3_controller:
    type: effort_controllers/JointTrajectoryController
    joint: katana_motor3_pan_joint
    pid: {p: 3.0, i: 4.5, d: 1.8, i_clamp: 0.0}

  katana_arm_m4_controller:
    type: effort_controllers/JointTrajectoryController
    joint: katana_motor4_pan_joint
    pid: {p: 8.0, i: 3.0, d: 3.0, i_clamp: 0.0}

  katana_arm_m5_controller:
    type: effort_controllers/JointTrajectoryController
    joint: katana_motor5_wrist_roll_joint
    pid: {p: 1, i: 0.0, d: 0.0, i_clamp: 0.0}
  
constraints:
    goal_time: 0.6                    # Defaults to 0.0 (is enforced!)
    stopped_velocity_tolerance: 0.02  # Defaults to 0.01
    katana_motor1_pan_joint:
      #trajectory: 0.05                # Defaults to zero (i.e., tolerance is not enforced)
      goal: 0.05                      # Defaults to zero (i.e., tolerance is not enforced)
    katana_motor2_lift_joint:
      goal: 0.05
    katana_motor3_lift_joint:
      goal: 0.05
    katana_motor4_lift_joint:
      goal: 0.05
    katana_motor5_wrist_roll_joint:
      goal: 0.05

